In [2]:
# create 2D array and 1D array

import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar=np.array([1])
print(arr)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1]


In [3]:
res=arr+ar
print(res)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
res=arr*ar
print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Create array of size 4x3 and 1x3. find the result of (4x3) x (1x3)

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array([[9,8,7]])
print(a)
print("")
print(b)
print("")
res=a*b
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[9 8 7]]

[[ 9 16 21]
 [36 40 42]
 [63 64 63]
 [90 88 84]]


In [13]:
import numpy as np
arr=np.array([[10,20],[30,40]])
ar=np.array([[30,40]])
res=np.sum(arr,axis=0)
res1=np.sum(ar,axis=1)
print(res)
print("")
print(res1)

[40 60]

[70]


In [17]:
# create a reshape
import numpy as np
z=np.arange(1,13)
print(z.reshape(4,3))
print("")
print(z.reshape(6,2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [21]:
# create array of size 3x3 and perform temperature adjustment with the following data.
# 1.Create Array
# 2.create temp adjustment
# 3.multiply a1 with temp adjustment
# 4.Add each column

a1=np.array([[42,34,45],[23,32,12],[89,67,45]])
print(a1)
print("")

temp_adj=np.array([[0.5,-1.5,2]])
print(temp_adj)
print("")

res=a1*temp_adj
print(res)
print("")

res1=np.sum(res,axis=0)
print(res1)


[[42 34 45]
 [23 32 12]
 [89 67 45]]

[[ 0.5 -1.5  2. ]]

[[  21.   -51.    90. ]
 [  11.5  -48.    24. ]
 [  44.5 -100.5   90. ]]

[  77.  -199.5  204. ]


In [3]:
# Create an array of 3 products over 4 months enter its sales each month calculate their highest month wise product sales.
# 1. find the maximum product sold.
# 2. find the avg number of product sold in total.

import numpy as np
ar=np.array([[20,30,40,50],[160,70,80,120],[200,67,125,78]])
maximum=np.max(ar,axis=0)
print(maximum)
print("")
maxi=np.max(ar,axis=1)
print(maxi)
print("")
av=np.avg(ar,axis=1)
print(av)

[200  70 125 120]

[ 50 160 200]



AttributeError: module 'numpy' has no attribute 'avg'